on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'build-number-*'
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.TOKEN}}
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"

    - run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Decode google-services.json
      env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo $FIREBASE_CONFIG > android/app/google-services.json

    - name: Build release APKs
      run: flutter build apk --release --build-number=$BUILD_NUMBER

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: alpha-testers
        file: build/app/outputs/apk/release/app-release.apk
